# Generated by Django 4.0.6 on 2022-07-16 16:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('descriptions', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='descriptions')),
                ('background_image', models.FileField(upload_to='carousel-image', verbose_name='background_image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'carousel',
                'verbose_name_plural': 'carousels',
                'ordering': ['title'],
            },
        ),
    ]
