# Generated by Django 4.0.6 on 2022-07-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpsubcategory',
            name='title',
        ),
        migrations.AddField(
            model_name='helpsubcategory',
            name='subcategory',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='title'),
        ),
    ]
