# Generated by Django 4.0.6 on 2022-07-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_remove_helpsubcategory_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpsubcategory',
            options={'verbose_name': 'subcategory', 'verbose_name_plural': 'subcategories'},
        ),
    ]
