# Generated by Django 4.0.6 on 2022-07-16 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_alter_helpsubcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpmodel',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='help.helpsubcategory', verbose_name='subcategory'),
        ),
    ]
