# Generated by Django 4.0.6 on 2022-08-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordermodel_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='upon_receipt',
            field=models.CharField(blank=True, choices=[('email', 'Получить почтой'), ('deliver', 'Доставить курьером'), ('ru_mail', 'Получить из почтамата')], max_length=100, null=True),
        ),
    ]
