# Generated by Django 4.0.6 on 2022-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_ordermodel_upon_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='phone',
            field=models.PositiveIntegerField(max_length=50, null=True),
        ),
    ]
