# Generated by Django 4.0.6 on 2022-08-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_ordermodel_email_alter_ordermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='upon_receipt',
            field=models.CharField(blank=True, choices=[('email', 'Получить почтой'), ('deliver', 'Доставить курьером'), ('ru_mail', 'Получить из почтамата')], max_length=200, null=True),
        ),
    ]
