# Generated by Django 4.0.6 on 2022-08-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_ordermodel_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
