# Generated by Django 4.0.6 on 2022-08-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_ordermodel_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('flat_office', models.CharField(max_length=100, verbose_name='flat_office')),
                ('entrance', models.CharField(max_length=100, verbose_name='entrance')),
                ('intercom', models.CharField(max_length=100, verbose_name='intercom')),
                ('floor', models.CharField(max_length=100, verbose_name='floor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
