# Generated by Django 4.0.6 on 2022-08-15 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_addressmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='orders.addressmodel'),
        ),
    ]
