# Generated by Django 4.0.6 on 2022-08-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_alter_reviewmodel_product'),
        ('orders', '0019_ordermodel_coupon_ordermodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='products.productmodel'),
        ),
    ]
