# Generated by Django 4.0.6 on 2022-08-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_ordermodel_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='product',
        ),
    ]
