# Generated by Django 4.0.6 on 2022-08-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_ordermodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user_order',
            field=models.CharField(blank=True, choices=[('process', 'В процессе'), ('cancel', 'Заказ отменен'), ('delivery', 'Выполняется доставка'), ('success', 'Товар получен')], default='process', max_length=200, null=True),
        ),
    ]
