# Generated by Django 4.0.6 on 2022-08-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_orderitem_user_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user_order',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user_order',
            field=models.CharField(blank=True, choices=[('process', 'В процессе'), ('cancel', 'Заказ отменен'), ('delivery', 'Выполняется доставка'), ('success', 'Товар получен')], default='В процессе', max_length=200, null=True),
        ),
    ]
