# Generated by Django 4.0.6 on 2022-08-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_ordermodel_user_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='user_order',
            new_name='status',
        ),
    ]
