# Generated by Django 4.0.6 on 2022-08-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_ordermodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='first_name',
        ),
    ]
