# Generated by Django 4.0.6 on 2022-08-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_remove_ordermodel_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
