# Generated by Django 4.0.6 on 2022-08-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_ordermodel_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='phone',
        ),
    ]
