# Generated by Django 4.0.6 on 2022-08-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_ordermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
