# Generated by Django 4.0.6 on 2022-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
