# Generated by Django 4.0.6 on 2022-07-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.FileField(null=True, upload_to='image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.FileField(null=True, upload_to='image', verbose_name='image'),
        ),
    ]
