# Generated by Django 4.0.6 on 2022-07-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['title'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='discount'),
        ),
    ]
