# Generated by Django 4.0.6 on 2022-07-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productmodel_real_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='count',
        ),
    ]
