# Generated by Django 4.0.6 on 2022-07-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productmodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
