# Generated by Django 4.0.6 on 2022-07-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_ratingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='ratings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='products.ratingmodel'),
        ),
    ]
