# Generated by Django 4.0.6 on 2022-07-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_ratingstar_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
    ]
