# Generated by Django 4.0.6 on 2022-07-23 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_reviewmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCharacteristicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=300, verbose_name='data')),
                ('number', models.CharField(max_length=300, verbose_name='data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characteristics', to='products.productmodel', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product_characteristic',
                'verbose_name_plural': 'product_characteristics',
            },
        ),
    ]
