# Generated by Django 4.0.6 on 2022-07-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_reviewmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
