# Generated by Django 4.0.6 on 2022-08-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_subcategorymodel_productmodel_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategorymodel',
            old_name='subcategory',
            new_name='title',
        ),
    ]
