# Generated by Django 4.0.6 on 2022-08-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_subcategorymodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
    ]
