# Generated by Django 4.0.6 on 2022-08-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_ordermodel_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='status',
            field=models.IntegerField(choices=[(10, 'Open'), (20, 'Submitted')], default=10),
        ),
    ]
