# Generated by Django 4.0.6 on 2022-08-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_alter_addressmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketline',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basketline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='basketmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='AddressModel',
        ),
        migrations.DeleteModel(
            name='BasketLine',
        ),
        migrations.DeleteModel(
            name='BasketModel',
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
