# Generated by Django 4.0.6 on 2022-08-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_productmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='user',
        ),
    ]
