# Generated by Django 4.0.6 on 2022-08-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_remove_productmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom', models.CharField(max_length=200, verbose_name='custom')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='products.productmodel', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product custom',
                'verbose_name_plural': 'product customers',
            },
        ),
    ]
