# Generated by Django 4.0.6 on 2022-08-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_productcustommodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustommodel',
            name='number',
            field=models.PositiveIntegerField(null=True, verbose_name='number'),
        ),
    ]
