# Generated by Django 4.0.6 on 2022-08-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_productcustommodel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='name_customer',
            field=models.CharField(max_length=200, null=True, verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='number_name_customer',
            field=models.CharField(max_length=200, null=True, verbose_name='number_name_customer'),
        ),
    ]
