# Generated by Django 4.0.6 on 2022-08-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_alter_reviewmodel_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=200, verbose_name='custom_name')),
                ('custom_number', models.CharField(max_length=200, verbose_name='custom_number')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_names', to='products.productmodel', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product_custom_name',
                'verbose_name_plural': 'product_custom_names',
            },
        ),
    ]
