# Generated by Django 4.0.6 on 2022-08-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_productcustomnamemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='name_customer',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='number_name_customer',
        ),
    ]
